set (WITH_GLX_EXAMPLE OFF CACHE STRING "" FORCE)

set (WITH_EGL_EXAMPLE ON CACHE STRING "" FORCE)

set (WITH_X11_GLES ON CACHE STRING "" FORCE)

set (WITH_DESKTOP OFF CACHE STRING "" FORCE)

set (WITH_FORCE_COPY OFF CACHE STRING "" FORCE)

set (WITH_TESTS OFF CACHE STRING "" FORCE)

set (DBUS_ARCH_INCLUDE_DIR /usr/lib/<YOUR ARCHITECTURE>/dbus-1.0/include CACHE STRING "" FORCE)
